import Head from "next/head";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Link from "next/link";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello world</h1>
      <div>
        {posts.map(({ slug, data: { image, title, excerpt, date } }) => (
          <div key={slug}>
            <Link href={`/posts/${slug}`}>
              <a>
                <h2>{title}</h2>
                <p>{date}</p>
                <p>{excerpt}</p>
                <img src={image} />
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const files = fs.readdirSync(path.join("posts"));

  const posts = files.map((filename) => {
    const slug = path.parse(filename).name;
    const file = fs.readFileSync(path.join("posts", filename), "utf-8");
    const { data } = matter(file);

    return {
      slug,
      data,
    };
  });

  posts.sort((a, b) => new Date(b.data.date) - new Date(a.data.date));

  return {
    props: {
      posts,
    },
  };
}
